name: 'soccer_dbt'
version: '1.0.0'
config-version: 2

profile: 'soccer_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target"]

models:
  soccer_dbt:
    +materialized: table